import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-gray-50 text-gray-900">
        {/* Header */}
        <header className="bg-blue-600 text-white p-4 shadow-md" style={{
          backgroundColor: "#bada55"
        }}>
          <div className="container mx-auto text-center text-2xl font-bold">
            My Next.js App Header
          </div>
        </header>

        {/* Main content */}
        <main className="flex-1 container mx-auto p-6" >
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-gray-800 text-gray-200 p-4" style={{
          width: '100%',
          minHeight: "30px",
          backgroundColor: '#f9f9f9',
          border: '1px solid #ddd',
        }}>
          <div className="container mx-auto text-center">
            © {new Date().getFullYear()} My Next.js App. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  )
}